version: "3.8"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'

volumes:
  db-data:
    driver: local