version: "3.8"
services:
  api:
    build: .
    command: /bin/air
    ports: 
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/go/src/app
    tty: true # 標準出力先を標準入力元のターミナルと同じに(colorizeなどが有効化されるなど)
    depends_on: 
      - mysql
    # environment:
    #   AUTH_DB_HOST: mysql
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'

volumes:
  db-data:
    driver: local
