name: gotest
on: [push, pull_request]

jobs: 
  run-gotest: 
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run go test
        run: make test FLAGS="-race -parallel 3 -coverprofile='coverage.txt'"
      - name: upload coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
