// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/shellingford330/auth/domain/service"
	"github.com/shellingford330/auth/infra/rdb"
	"github.com/shellingford330/auth/infra/rdb/mysql"
	"github.com/shellingford330/auth/presentation/grpc"
	"github.com/shellingford330/auth/usecase"
)

// Injectors from wire.go:

func InitServer() (*grpc.Server, error) {
	db := _wireDBValue
	userRepository := rdb.NewUserRepository(db)
	userQueryService := rdb.NewUserQueryService(db)
	sessionRepository := rdb.NewSessionRepository(db)
	sessionService := service.NewSessionService(sessionRepository)
	userUseCase := usecase.NewUserUseCase(userRepository, userQueryService, sessionService)
	accountRepository := rdb.NewAccountRepository(db)
	accountUseCase := usecase.NewAccountUseCase(accountRepository)
	sessionQueryService := rdb.NewSessionQueryService(db)
	sessionUseCase := usecase.NewSessionUseCase(sessionRepository, sessionQueryService)
	useCase := usecase.NewUseCase(userUseCase, accountUseCase, sessionUseCase)
	handler := grpc.NewHandler(useCase)
	server := grpc.NewServer(handler)
	return server, nil
}

var (
	_wireDBValue = mysql.DB
)
